### ISSUE TITLE
Allow exporting configuration

### ISSUE THREAD

**Issue by andidavies92** [Stack-in-a-box/chrome-domain-watermarker#32]
# Requirements

_Must_ adhere to the schema that was designed in https://github.com/Stack-in-a-box/chrome-domain-watermarker/issues/31.

# Tasks

- [ ] Add _"export"_ button/link to UI.
- [ ] Write code to serialise the configuration.
- [ ] Handle the button click with a save dialogue.

# Estimate

1 hour.
