### ISSUE TITLE
Allow importing configuration

### ISSUE THREAD

**Issue by andidavies92** [Stack-in-a-box/chrome-domain-watermarker#33]
# Requirements

* _Must_ handle all previous versions of the configuration schema.
* _Must_ round-trip the configuration successfully on export and re-import.
* _Could_ include unit tests to verify the round-tripping.

# Tasks

- [ ] Add _"import"_ button/link to UI.
- [ ] Write code to parse the serialised configuration.
- [ ] Validate and interpret the parsed configuration.
- [ ] Update the stored configuration for the extension and re-render.

# Estimate

2 hours.
