### ISSUE TITLE
Set-up a mechanism for testing enterprise deployment

### ISSUE THREAD

**Issue by andidavies92** [Stack-in-a-box/chrome-domain-watermarker#34]
# Overview

This will require some assistance from work colleagues to set-up. Ideally, this will include an Active Directory domain user account (that I can log-into in a domain-connected Windows VM) and an account with sufficient admin privileges (preferably one that I can access) that will let me create a group policy to apply to the test user.

# Tasks

- [ ] Liaise w/ colleagues to arrange the work.
- [ ] Get the necessary infrastructure provisioned and set-up for testing.
- [ ] Create a group policy as the domain admin that force-installs Chrome.
- [ ] Log-in as the domain user to verify that Chrome was automatically installed.

# Estimate

4-8 hours.
